# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=6)),
                ('uploaded_date', models.DateTimeField(verbose_name='Upload Datetime')),
                ('life', models.IntegerField(default=0)),
                ('sha1', models.CharField(max_length=40)),
            ],
        ),
    ]
