# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='alias',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
